### ISSUE TITLE
Handle server crash on post / route

### ISSUE THREAD

**Issue by median-man** [race-finder/race-finder#21]
The server crashes (and UI hangs on loading view) when the user clicks on the search button without logging in.

Configuration when error was produced:
* OS: Windows 7 Pro
* Browser: Chrome
* Running on localhost for server and database in "development" environment

Command Line Output:
```bash
{ state: 'CA', startDate: '1/20/2018', endDate: '5/6/2018' }
Unhandled rejection SequelizeValidationError: notNull Violation: UserId cannot be null
    at Promise.all.then (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\sequelize\lib\instance-validator.js:77:15)
    at tryCatcher (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise_array.js:144:14)
    at Promise._settlePromise (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

https://api.wunderground.com/api/4c190f89c44f0e65/history_20170506/q/CA/Eureka.json
https://api.wunderground.com/api/4c190f89c44f0e65/history_20170429/q/CA/Carmel.json
https://api.wunderground.com/api/4c190f89c44f0e65/history_20170310/q/CA/Catalina_Island.json
X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\controllers\weather.js:55
        temps.min = parseFloat(JSON.parse(body).history.dailysummary[0].mintempi);
                                                       ^

TypeError: Cannot read property 'dailysummary' of undefined
    at Request._callback (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\controllers\weather.js:55:56)
    at Request.self.callback (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by median-man** [comment]
The crash doesn't care if user is logged in or not. I was able to get the same errors in the log when I was logged in. The environment is the same as before.

```bash command line
{ state: 'CA', startDate: '1/20/2018', endDate: '5/6/2018' }
Unhandled rejection SequelizeValidationError: notNull Violation: UserId cannot be null
    at Promise.all.then (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\sequelize\lib\instance-validator.js:77:15)
    at tryCatcher (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise_array.js:144:14)
    at Promise._settlePromise (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

https://api.wunderground.com/api/4c190f89c44f0e65/history_20170506/q/CA/Eureka.json
https://api.wunderground.com/api/4c190f89c44f0e65/history_20170429/q/CA/Carmel.json
https://api.wunderground.com/api/4c190f89c44f0e65/history_20170310/q/CA/Catalina_Island.json
X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\controllers\weather.js:55
        temps.min = parseFloat(JSON.parse(body).history.dailysummary[0].mintempi);
                                                       ^

TypeError: Cannot read property 'dailysummary' of undefined
    at Request._callback (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\controllers\weather.js:55:56)
    at Request.self.callback (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by median-man** [comment]
The second error--`TypeError: Cannot read property 'dailysummary' of undefined`-- is unrelated to the first error which does not crash the server. Added an error callback parameter to addSearchToDB for future cases where granular error handling is required.

**Comment by median-man** [comment]
See issues #27 and #26.
