### ISSUE TITLE
seeds.js error

### ISSUE THREAD

**Issue by median-man** [race-finder/race-finder#22]
After initializing the schema, seed.js throws an error. It appears to seed the database races and locations tables correctly. Further investigation is needed.

Requirements:
* no error thrown when seed.js is run
* verify data integrity after seeding db and display a message in the console.

**Comment by median-man** [comment]
Error from the node terminal output after initializing the schema and running `$ node db/seed.js` on the command line:
```
Unhandled rejection SequelizeValidationError: notNull Violation: city cannot be null,
notNull Violation: state cannot be null
    at Promise.all.then (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\sequelize\lib\instance-validator.js:77:15)
    at tryCatcher (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise_array.js:144:14)
    at Promise._settlePromise (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date fo
rmats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 11/12/2017, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\moment\moment.js:320:94)
    at configFromString (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\moment\moment.js:2178:11)
    at configFromInput (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\moment\moment.js:2547:9)
    at prepareConfig (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\moment\moment.js:2530:9)
    at createFromConfig (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\moment\moment.js:2497:40)
    at createLocalOrUTC (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\moment\moment.js:2584:12)
    at createLocal (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\moment\moment.js:2588:12)
    at hooks (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\moment\moment.js:16:25)
    at model._sanitize (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\sequelize\lib\data-types.js:398:12)
    at model.set (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\sequelize\lib\model.js:3295:63)
    at model.set (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\sequelize\lib\model.js:3235:18)
    at model._initValues (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\sequelize\lib\model.js:3051:10)
    at model.Model (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\sequelize\lib\model.js:3000:10)
    at Race (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\sequelize\lib\sequelize.js:334:19)
    at Function.build (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\sequelize\lib\model.js:1932:12)
    at Function.create (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\sequelize\lib\model.js:1983:17)
    at DB.Location.create.then (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\db\seed.js:46:11)
    at tryCatcher (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\bluebird\js\release\promise.js:693:18)
```
