### ISSUE TITLE
Fix Server Crash when dialysummary is undefined.

### ISSUE THREAD

**Issue by median-man** [race-finder/race-finder#26]
I haven't been able to reproduce the error in subsequent testing since it first showed up. It appears to occur when there is no body returned from the wunderground api in weather.js.
```
X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\controllers\weather.js:55
        temps.min = parseFloat(JSON.parse(body).history.dailysummary[0].mintempi);
                                                       ^

TypeError: Cannot read property 'dailysummary' of undefined
    at Request._callback (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\controllers\weather.js:55:56)
    at Request.self.callback (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (X:\Users\John\Documents\code\Coding Bootcamp\projects\race-finder\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by median-man** [comment]
unable to reproduce the crash. closing this bug.
